name: teaching-nextflow
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - nextflow
  - nf-core
  - conda-forge::biopython
  - conda-forge::markdown
  - conda-forge::pymdown-extensions
  - conda-forge::pygments
  - bioconda::fastqc
  - samtools
  - bwa
  - podman
  - pip
  - pip:
    - bash_kernel