FROM nfcore/base:1.9

# Create the conda environment

# Make sure conda installation is in the PATH 
# and so are python modules - they should be in PYTHONPATH (tip: add [..]/lib/python3.8/site-packages)


